export const documentData={
    data:`installation_001,"How long does it take to install a solar panel system?","A typical residential solar installation requires approximately two to four days. The exact duration depends on factors like the system's size, the condition of the roof, and prevailing weather conditions.",installation
installation_002,"Do I need any government approval before installing solar panels?","Yes, government approval is required. Most regions mandate approval from the local electricity board and municipality before installation can begin. This ensures the system complies with all safety regulations and grid standards.",installation
installation_003,"Can solar panels be installed on flat roofs?","Yes, solar panels can be installed on flat roofs. We use specialized tilt-mounted structures that angle the panels to capture the optimal amount of sunlight throughout the day.",installation
installation_004,"What are the prerequisites for solar installation at my home?","The primary prerequisites for a home solar installation are having a structurally stable roof or ground space and receiving at least four to five hours of direct, unobstructed sunlight each day.",installation
installation_005,"Who will handle the installation process?","All installations are conducted by certified SunSmart technicians who ensure adherence to safety protocols and performance standards.",installation
installation_006,"Is there a site inspection before installation?","Yes. A site inspection is mandatory to assess roof structure, sunlight availability, and electrical configuration before installation approval.",installation
installation_007,"Can I expand my solar system capacity later?","Yes. Systems can be expanded based on inverter compatibility and roof space availability. Our team will evaluate feasibility during assessment.",installation
installation_008,"How are panels mounted on tiled roofs?","Panels on tiled roofs are installed using non-invasive mounting brackets to ensure both stability and roof integrity.",installation
installation_009,"What is the expected lifespan of a solar installation?","A properly installed and maintained solar system has an expected lifespan of 25 to 30 years. The longevity depends on the quality of the solar panels and the inverter.",installation
installation_010,"Do I need to be present during installation?","It is advisable to be available during the first day for access and briefing. Afterward, the process can continue under supervision.",installation
billing_011,"How can I view and pay my solar energy bills?","You can access your billing history and make payments through the SunSmart mobile application or customer portal.",billing
billing_012,"Is financing available for solar panel purchases?","Yes. We provide flexible EMI and lease options in collaboration with recognized financial institutions.",billing
billing_013,"Do I need to pay a security deposit?","A refundable security deposit may be applicable depending on the selected plan and payment model.",billing
billing_014,"How can I obtain a copy of my invoice?","Invoices are available in PDF format under the Billing section of your customer dashboard.",billing
billing_015,"Can I change my billing address?","Yes. You can update your billing address through your account settings or by contacting customer service.",billing
maintenance_016,"How often should solar panels be cleaned?","To maintain peak efficiency and energy production, we recommend cleaning your solar panels every three to four months.",maintenance
maintenance_017,"Who is responsible for periodic maintenance?","Maintenance is typically managed by SunSmart under annual service agreements or as per customer contracts.",maintenance
maintenance_018,"Does dust accumulation affect performance?","Yes. Excessive dust can reduce energy output by 5–10%. Regular cleaning ensures optimal performance.",maintenance
maintenance_019,"Can I clean panels myself?","Yes, provided you use non-abrasive materials and safety equipment. Avoid using harsh chemicals.",maintenance
maintenance_020,"How can I schedule a maintenance visit?","Maintenance visits can be scheduled through the SunSmart mobile app or by contacting our service helpline.",maintenance
performance_021,"What affects the performance of solar panels?","Performance may be influenced by shading, dust accumulation, temperature, and panel orientation.",performance
performance_022,"What is the efficiency rate of SunSmart solar panels?","Our panels operate at an efficiency range of 18–22%, depending on model and environmental factors.",performance
performance_023,"Why is my system producing less power on cloudy days?","Solar panels generate less electricity in low sunlight, but the system continues to function efficiently even on cloudy days.",performance
performance_024,"How can I track my energy generation?","You can monitor daily and monthly energy production through the SunSmart mobile dashboard.",performance
performance_025,"Does temperature impact energy generation?","Yes. High temperatures can slightly reduce panel output, though modern panels are designed to minimize this effect.",performance
troubleshooting_026,"What should I do if my inverter is not turning on?","First, check the main switch, circuit breakers, and all connections. If the issue persists, please contact our support team immediately.",troubleshooting
troubleshooting_027,"Why is my system not generating power?","This may occur due to shading, faulty wiring, or an inverter malfunction. We recommend scheduling a diagnostic inspection via the app.",troubleshooting
troubleshooting_028,"My inverter shows a red fault light. What does it mean?","A red indicator generally signifies a system error or a grid issue. Please report the fault for service assistance without delay.",troubleshooting
troubleshooting_029,"What happens if the grid power fails?","For safety, the solar system automatically shuts down during a grid outage and resumes once grid power is restored. This is known as anti-islanding.",troubleshooting
troubleshooting_030,"Can I restart the inverter myself?","Yes, you can follow the reboot procedure in the user manual. If the problem is unresolved after a restart, please seek professional assistance.",troubleshooting
warranty_031,"What is the warranty period for solar panels?","SunSmart offers a 25-year performance warranty and a 10-year product warranty on our solar panels.",warranty
warranty_032,"Is the inverter covered under warranty?","Yes. Inverters typically come with a 5-year manufacturer warranty, which can be extended to 10 years.",warranty
warranty_033,"What voids the warranty coverage?","Any unauthorized repairs, physical damage, or misuse of the equipment may void the warranty coverage.",warranty
warranty_034,"How do I claim warranty service?","You can submit a warranty claim through your account dashboard by providing purchase details and a description of the fault.",warranty
warranty_035,"Can warranty be transferred to a new property owner?","Yes. The warranty can be transferred to a new owner upon submission of ownership verification and documentation.",warranty
environment_036,"How does solar energy help the environment?","Solar energy reduces dependence on fossil fuels, thereby lowering greenhouse gas emissions and pollution.",environment
environment_037,"What is the carbon offset from an average solar system?","A standard 5 kW residential system can offset approximately 6 to 8 tons of CO₂ emissions annually.",environment
environment_038,"Are solar panels recyclable?","Yes. Most components, including the glass and aluminum frames, are recyclable through approved facilities at the end of their lifespan.",environment
environment_039,"Do solar panels contain harmful materials?","No. SunSmart panels are built using safe, regulated materials that are compliant with international environmental standards.",environment
environment_040,"Does solar power reduce electricity bills significantly?","Yes. A properly sized solar power system can reduce your monthly electricity costs by 50% to 90%, depending on your energy consumption.",environment
app_support_041,"How do I log in to the SunSmart mobile app?","Download the app from your device’s app store and log in using your registered email and password.",app_support
app_support_042,"Can I reset my account password?","Yes. Use the 'Forgot Password' option on the login screen to securely reset your credentials via email.",app_support
app_support_043,"How can I view system performance on the app?","Navigate to the 'Dashboard' section in the app to monitor both real-time and historical system performance data.",app_support
app_support_044,"Is the app available for iOS and Android?","Yes. The SunSmart app is available for download on both the Apple App Store for iOS and the Google Play Store for Android.",app_support
app_support_045,"How do I update my contact information in the app?","Open the 'Profile' section within the app and update your personal details under the 'Account Settings' menu.",app_support
billing_046,"What is net metering and how does it work?","Net metering is a billing mechanism that credits you for the excess electricity your solar panels generate and send back to the grid. These credits offset the cost of power you draw from the grid at night.",billing
performance_047,"What is the role of a solar battery?","A solar battery stores excess energy generated during the day. This stored energy can be used at night or during a power outage, providing energy independence and backup power.",performance
billing_048,"What is the typical return on investment for a solar system?","The typical payback period, or return on investment (ROI), for a residential solar system is between 6 to 10 years, after which the energy you generate is virtually free.",billing
installation_049,"What is the difference between monocrystalline and polycrystalline panels?","Monocrystalline panels (black) are more efficient and made from a single silicon crystal. Polycrystalline panels (blue) are less expensive but slightly less efficient, made from multiple silicon fragments.",installation
performance_050,"What's the difference between a string inverter and microinverters?","A string inverter connects a series of panels to a single central unit. It's cost-effective, but shading on one panel can reduce output for the whole string. Microinverters are installed on each panel, optimizing individual performance and offering better monitoring, but at a higher cost.",performance
installation_051,"How do you determine the right size system for my home?","We determine the optimal system size by analyzing your last 12 months of electricity bills, assessing your roof's available unshaded area and orientation, and discussing your future energy needs, such as adding an electric vehicle.",installation
performance_052,"Do solar panels lose efficiency over time?","Yes, all solar panels experience a slow, predictable rate of degradation, typically around 0.5% per year. Our 25-year performance warranty guarantees that your panels will still operate at or above 80-85% of their original output at the end of the warranty period.",performance
billing_053,"What happens if I sell my house with the solar system?","If you own the system, it adds value to your home and the warranty can be transferred to the new owner. If you have a lease or loan, the agreement typically needs to be transferred to the new buyer or paid off at the time of sale.",billing
installation_054,"Do I need to update my homeowner's insurance?","Yes, we highly recommend you contact your insurance provider to add the solar system to your homeowner's policy. This ensures it's covered against unforeseen events like severe weather or fire.",installation
maintenance_055,"What if I need to replace my roof in the future?","If your roof needs replacement, the solar panels and mounting equipment must be professionally removed and then reinstalled. This 'remove and reinstall' service can be scheduled with our team and involves an additional cost.",maintenance
performance_056,"Are solar panels durable enough to withstand hail and snow?","Absolutely. Our panels are manufactured to strict standards and are tested to withstand hail up to 1 inch in diameter and heavy snow loads. Their durable, tempered glass surface is designed for harsh weather conditions.",performance
troubleshooting_057,"If I have a solar battery, will I have power during a blackout?","Yes. A major advantage of a solar battery is providing backup power. During a grid outage, your system's transfer switch will automatically disconnect from the grid and power your essential appliances using the stored battery energy.",troubleshooting
troubleshooting_058,"Why is my electricity bill still high after installing solar panels?","This can be due to increased energy consumption at home, a period of unusually cloudy weather, or a system performance issue. Check your consumption against your system's production in the SunSmart app to identify the cause.",troubleshooting
maintenance_059,"How do I stop birds from nesting under my solar panels?","We can install a 'critter guard', which is a protective wire mesh barrier around the perimeter of your solar array. This effectively prevents birds and other pests from accessing the space underneath the panels without impacting performance.",maintenance
performance_060,"What is the difference between kW and kWh?","A kilowatt (kW) is a unit of power, representing the *rate* of energy generation at one moment. A kilowatt-hour (kWh) is a unit of energy, representing the total *amount* of electricity produced over a period of time. Your system has a size in kW, and it produces energy in kWh.",performance
billing_061,"What are the pros and cons of leasing versus buying a solar system?","Buying a system (with cash or a loan) has a higher upfront cost but provides the greatest long-term savings, ownership, and eligibility for tax credits. Leasing has little to no upfront cost and predictable monthly payments, but you do not own the system and the overall financial benefits are smaller.",billing
`
}